id: I28D0B885
legacy_id: P010705
ocr_import_info:
  bdrc_scan_id: W24771
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T13:34:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:48:20.051289+00:00'
last_modified: 2022-09-02 13:48:27.132206
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24771
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW24771
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱམས་པའི་སྨོན་ལམ་ཡོན་ཏན་གྱི་རྒྱ་མཚོ་ལ་རྣམ་བཤད་དད་པའི་ངང་མོ་རྣམ་པར་རྩེ་བ།
  author: གཞུང་བརྒྱ་པ་དངོས་གྲུབ་དཔལ་འབར།
statistics:
  ocr_word_mean_confidence_index: 0.7487912617609951
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I1KG12619:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12619
      total_pages: 36
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12619.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7487912617609951
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
