id: P010705
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:46.062114
source_metadata:
  id: bdr:W24771
  title: བྱམས་པའི་སྨོན་ལམ་ཡོན་ཏན་གྱི་རྒྱ་མཚོ་ལ་རྣམ་བཤད་དད་པའི་ངང་མོ་རྣམ་པར་རྩེ་བ།
  author: ''
  volumes:
    ca39c0eb9512487fa5dce0c8e60f5af8:
      image_group_id: I1KG12619
      title: ''
      volume_number: 1
      total_pages: 36
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
